# Generated by Django 4.2.6 on 2023-10-27 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_AddOrderLines'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 23, 27, 23, 933796, tzinfo=datetime.timezone.utc)),
        ),
    ]
